import {b} from '../config/timing';

// Sound design cue sheet. `at` is an absolute frame (30 fps); files live in
// public/audio/sfx and are generated by scripts/generate_audio.py.

export type Sfx =
  | 'click'
  | 'tick'
  | 'hover'
  | 'pop'
  | 'pop_soft'
  | 'blip'
  | 'blip_hi'
  | 'whoosh'
  | 'whoosh_fast'
  | 'whoosh_big'
  | 'swoosh_up'
  | 'reverse_swell'
  | 'impact'
  | 'impact_soft'
  | 'riser'
  | 'shimmer'
  | 'glint'
  | 'success'
  | 'bell'
  | 'member_chime'
  | 'card_insert'
  | 'unlock'
  | 'confetti'
  | 'chat'
  | 'processing';

export type Cue = {at: number; sfx: Sfx; volume: number};

const c = (at: number, sfx: Sfx, volume: number): Cue => ({at: Math.max(0, Math.round(at)), sfx, volume});

export const CUES: Cue[] = [
  // ── hook
  c(0, 'reverse_swell', 0.3),
  c(3, 'whoosh', 0.3),
  c(b(1) - 3, 'swoosh_up', 0.45),
  c(b(1), 'impact_soft', 0.5),
  c(27, 'whoosh_fast', 0.22),
  c(b(3), 'click', 0.55),
  c(b(3) + 1, 'pop', 0.45),
  c(b(3) + 1, 'whoosh_fast', 0.45),
  c(b(3) + 2, 'glint', 0.3),
  c(b(4), 'impact', 0.58),
  c(b(5), 'shimmer', 0.42),
  c(b(6) - 2, 'whoosh_fast', 0.3),
  c(b(6) + 5, 'pop', 0.5),
  c(b(6) + 9, 'whoosh_big', 0.55),

  // ── channel page
  c(b(8) + 2, 'whoosh_big', 0.38),
  ...[0, 1, 2, 3, 4, 5].map((i) => c(b(8) + 9 + i * 5, i % 2 ? 'blip_hi' : 'blip', 0.14)),
  c(b(12.4), 'hover', 0.3),
  c(b(13), 'click', 0.55),
  c(b(13) + 3, 'pop_soft', 0.45),
  c(b(13) + 6, 'bell', 0.4),
  c(b(14.2), 'whoosh', 0.28),
  c(b(15.2), 'hover', 0.3),
  c(b(15.7), 'glint', 0.38),

  // ── join dialog
  c(b(17), 'click', 0.55),
  c(b(17) + 2, 'swoosh_up', 0.55),
  c(b(17) + 7, 'pop_soft', 0.4),
  c(b(17) + 11, 'whoosh_fast', 0.28),
  ...[0, 1, 2].map((i) => c(b(17) + 15 + i * 4, 'tick', 0.22)),
  c(b(19), 'whoosh', 0.35),
  ...[0, 1, 2, 3].map((i) => c(b(20.3) + i * 10.5, 'blip_hi', 0.18)),
  c(b(23.2), 'hover', 0.35),
  c(b(24.6), 'glint', 0.35),
  c(b(26), 'click', 0.55),
  c(b(26.4), 'whoosh_fast', 0.45),
  c(b(26.6), 'whoosh', 0.38),

  // ── checkout
  c(b(27) + 1, 'pop_soft', 0.5),
  ...[0, 1, 2, 3].map((i) => c(b(27) + 13 + i * 5, 'tick', 0.14)),
  c(b(30.1), 'whoosh_big', 0.5),
  c(b(31.9) - 1, 'card_insert', 0.8),
  c(b(32.4), 'whoosh', 0.22),
  c(b(34.2), 'hover', 0.3),
  c(b(35), 'click', 0.55),
  c(b(35) + 3, 'processing', 0.42),
  c(b(38), 'success', 0.7),
  c(b(38), 'pop', 0.35),
  c(b(38) + 1, 'confetti', 0.5),
  c(b(40), 'riser', 0.62),
  c(b(44) - 27, 'reverse_swell', 0.55),

  // ── drop
  c(b(44), 'impact', 0.72),
  c(b(44) + 1, 'confetti', 0.6),
  c(b(44) + 4, 'shimmer', 0.4),
  c(b(44) + 10, 'swoosh_up', 0.38),
  c(b(44) + 26, 'glint', 0.35),
  c(b(44) + 32, 'pop', 0.4),
  ...[0, 1, 2, 3, 4, 5].map((i) => c(b(46) + i * 5, i % 2 ? 'blip_hi' : 'blip', 0.24)),
  c(b(51) - 3, 'whoosh', 0.45),
  c(b(52.2), 'pop', 0.5),
  c(b(52.2) + 1, 'glint', 0.4),
  c(b(54.5), 'hover', 0.3),
  c(b(55), 'click', 0.55),
  c(b(55.3), 'whoosh_fast', 0.45),

  // ── perks
  c(b(56) - 2, 'whoosh', 0.3),
  c(b(56), 'whoosh_fast', 0.45),
  c(b(57.4) + 1, 'member_chime', 0.6),
  c(b(58.6) + 1, 'chat', 0.5),
  c(b(59.7) + 1, 'chat', 0.45),
  c(b(60.6) + 1, 'chat', 0.4),
  c(b(61.4) + 1, 'chat', 0.4),
  c(b(61.9), 'whoosh_fast', 0.45),
  c(b(63.2), 'unlock', 0.45),
  c(b(63.7), 'unlock', 0.45),
  c(b(64.2), 'unlock', 0.45),
  c(b(65), 'whoosh_fast', 0.45),
  c(b(66.4), 'blip', 0.35),
  c(b(66.85), 'blip_hi', 0.35),
  c(b(67.3), 'glint', 0.4),
  c(b(67.5), 'whoosh', 0.35),

  // ── outro
  c(b(68) - 2, 'whoosh_big', 0.4),
  c(b(68), 'riser', 0.5),
  ...[0, 1, 2, 3, 4].map((i) => c(b(69.4) + i * 8, 'tick', 0.24)),
  c(b(72), 'impact', 0.62),
  c(b(72) + 1, 'pop', 0.5),
  c(b(72) + 2, 'shimmer', 0.4),
  c(b(72) + 4, 'swoosh_up', 0.35),
  c(b(72) + 16, 'pop_soft', 0.45),
  c(b(72) + 26, 'whoosh_fast', 0.22),
  c(b(75.1), 'hover', 0.3),
  c(b(75.5), 'click', 0.55),
  c(b(75.5) + 1, 'success', 0.55),
  c(b(75.5) + 2, 'confetti', 0.5),
  c(b(75.5) + 5, 'pop', 0.4),
];
